config/routes.rb
Rails.application.routes.draw do
  resources :operarios
  resources :procesos
  resources :maquinas
  resources :productos
  devise_for :users
  #get 'home/index'
  get 'home/costpage'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/maquina.rb
class Maquina < ApplicationRecord
end

app/controllers/maquinas_controller.rb
class MaquinasController < ApplicationController
  before_action :set_maquina, only: [:show, :edit, :update, :destroy]

  # GET /maquinas
  # GET /maquinas.json
  def index
    @maquinas = Maquina.all
  end

  # GET /maquinas/1
  # GET /maquinas/1.json
  def show
  end

  # GET /maquinas/new
  def new
    @maquina = Maquina.new
  end

  # GET /maquinas/1/edit
  def edit
  end

  # POST /maquinas
  # POST /maquinas.json
  def create
    @maquina = Maquina.new(maquina_params)

    respond_to do |format|
      if @maquina.save
        format.html { redirect_to @maquina, notice: 'Maquina was successfully created.' }
        format.json { render :show, status: :created, location: @maquina }
      else
        format.html { render :new }
        format.json { render json: @maquina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maquinas/1
  # PATCH/PUT /maquinas/1.json
  def update
    respond_to do |format|
      if @maquina.update(maquina_params)
        format.html { redirect_to @maquina, notice: 'Maquina was successfully updated.' }
        format.json { render :show, status: :ok, location: @maquina }
      else
        format.html { render :edit }
        format.json { render json: @maquina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maquinas/1
  # DELETE /maquinas/1.json
  def destroy
    @maquina.destroy
    respond_to do |format|
      format.html { redirect_to maquinas_url, notice: 'Maquina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maquina
      @maquina = Maquina.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maquina_params
      params.require(:maquina).permit(:Maquina, :CostoHora)
    end
end

app/helpers/maquinas_helper.rb
module MaquinasHelper
end

app/views/maquinas/_form.html.erb
<%= form_with(model: maquina) do |form| %>
  <% if maquina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(maquina.errors.count, "error") %> prohibited this maquina from being saved:</h2>

      <ul>
        <% maquina.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Maquina %>
    <%= form.text_field :Maquina %>
  </div>

  <div class="field">
    <%= form.label :CostoHora %>
    <%= form.text_field :CostoHora %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maquinas/edit.html.erb
<h1>Editing Maquina</h1>

<%= render 'form', maquina: @maquina %>

<%= link_to 'Show', @maquina %> |
<%= link_to 'Back', maquinas_path %>

app/views/maquinas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maquinas</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Maquina</th>
      <th>Costohora</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maquinas.each do |maquina| %>
      <tr>
        <td><%= maquina.Maquina %></td>
        <td><%= maquina.CostoHora %></td>
        <td><%= link_to 'Show', maquina %></td>
        <td><%= link_to 'Edit', edit_maquina_path(maquina) %></td>
        <td><%= link_to 'Destroy', maquina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maquina', new_maquina_path, class:"btn btn-outline-secondary" %>

app/views/maquinas/new.html.erb
<h1>New Maquina</h1>

<%= render 'form', maquina: @maquina %>

<%= link_to 'Back', maquinas_path %>

app/views/maquinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Maquina:</strong>
  <%= @maquina.Maquina %>
</p>

<p>
  <strong>Costohora:</strong>
  <%= @maquina.CostoHora %>
</p>

<%= link_to 'Edit', edit_maquina_path(@maquina), class:"btn btn-outline-secondary" %> 
<%= link_to 'Back', maquinas_path, class:"btn btn-outline-secondary" %>