config/routes.rb
Rails.application.routes.draw do
  resources :operarios
  resources :procesos
  resources :maquinas
  resources :productos
  devise_for :users
  #get 'home/index'
  get 'home/costpage'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def costpage
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'LaFeteChocolat', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        #nav bar options
        <li class="nav-item">
          <%= link_to "Iniciar sesion", new_user_session_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Editar perfil", edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Costos", home_costpage_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Maquinas", maquinas_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Operarios", operarios_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Procesos", procesos_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Productos", productos_path, class:"nav-link" %>
        </li>


      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/costpage.html.erb
<h1> Aca van los costos segun producto <h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>