config/routes.rb
Rails.application.routes.draw do
  resources :operarios
  resources :procesos
  resources :maquinas
  resources :productos
  devise_for :users
  #get 'home/index'
  get 'home/costpage'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/proceso.rb
class Proceso < ApplicationRecord
    belongs_to :producto
end

app/controllers/procesos_controller.rb
class ProcesosController < ApplicationController
  before_action :set_proceso, only: [:show, :edit, :update, :destroy]

  # GET /procesos
  # GET /procesos.json
  def index
    @procesos = Proceso.all
  end

  # GET /procesos/1
  # GET /procesos/1.json
  def show
  end

  # GET /procesos/new
  def new
    @proceso = Proceso.new
  end

  # GET /procesos/1/edit
  def edit
  end

  # POST /procesos
  # POST /procesos.json
  def create
    @proceso = Proceso.new(proceso_params)

    respond_to do |format|
      if @proceso.save
        format.html { redirect_to @proceso, notice: 'Proceso was successfully created.' }
        format.json { render :show, status: :created, location: @proceso }
      else
        format.html { render :new }
        format.json { render json: @proceso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /procesos/1
  # PATCH/PUT /procesos/1.json
  def update
    respond_to do |format|
      if @proceso.update(proceso_params)
        format.html { redirect_to @proceso, notice: 'Proceso was successfully updated.' }
        format.json { render :show, status: :ok, location: @proceso }
      else
        format.html { render :edit }
        format.json { render json: @proceso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procesos/1
  # DELETE /procesos/1.json
  def destroy
    @proceso.destroy
    respond_to do |format|
      format.html { redirect_to procesos_url, notice: 'Proceso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proceso
      @proceso = Proceso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proceso_params
      params.require(:proceso).permit(:CodProd, :Proceso, :Maquina, :Operario, :Ayudante)
    end
end

app/helpers/procesos_helper.rb
module ProcesosHelper
end

app/views/procesos/_form.html.erb
<%= form_with(model: proceso) do |form| %>
  <% if proceso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proceso.errors.count, "error") %> prohibited this proceso from being saved:</h2>

      <ul>
        <% proceso.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :CodProd %>
    <%= form.text_field :CodProd %>
  </div>

  <div class="field">
    <%= form.label :Proceso %>
    <%= form.text_field :Proceso %>
  </div>

  <div class="field">
    <%= form.label :Maquina %>
    <%= form.text_field :Maquina %>
  </div>

  <div class="field">
    <%= form.label :Operario %>
    <%= form.text_field :Operario %>
  </div>

  <div class="field">
    <%= form.label :Ayudante %>
    <%= form.text_field :Ayudante %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/procesos/edit.html.erb
<h1>Editing Proceso</h1>

<%= render 'form', proceso: @proceso %>

<%= link_to 'Show', @proceso %> |
<%= link_to 'Back', procesos_path %>

app/views/procesos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Procesos</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Codprod</th>
      <th>Proceso</th>
      <th>Maquina</th>
      <th>Operario</th>
      <th>Ayudante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @procesos.each do |proceso| %>
      <tr>
        <td><%= proceso.CodProd %></td>
        <td><%= proceso.Proceso %></td>
        <td><%= proceso.Maquina %></td>
        <td><%= proceso.Operario %></td>
        <td><%= proceso.Ayudante %></td>
        <td><%= link_to 'Show', proceso %></td>
        <td><%= link_to 'Edit', edit_proceso_path(proceso) %></td>
        <td><%= link_to 'Destroy', proceso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proceso', new_proceso_path, class:"btn btn-outline-secondary" %>

app/views/procesos/new.html.erb
<h1>New Proceso</h1>

<%= render 'form', proceso: @proceso %>

<%= link_to 'Back', procesos_path %>

app/views/procesos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codprod:</strong>
  <%= @proceso.CodProd %>
</p>

<p>
  <strong>Proceso:</strong>
  <%= @proceso.Proceso %>
</p>

<p>
  <strong>Maquina:</strong>
  <%= @proceso.Maquina %>
</p>

<p>
  <strong>Operario:</strong>
  <%= @proceso.Operario %>
</p>

<p>
  <strong>Ayudante:</strong>
  <%= @proceso.Ayudante %>
</p>

<%= link_to 'Edit', edit_proceso_path(@proceso), class:"btn btn-outline-secondary" %> 
<%= link_to 'Back', procesos_path, class:"btn btn-outline-secondary" %>